# Generated by Django 5.0.4 on 2024-04-05 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score1',
            new_name='firstParticipantScore',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='score2',
            new_name='secondParticipantScore',
        ),
        migrations.AddField(
            model_name='participant',
            name='match',
            field=models.ManyToManyField(related_name='participants', to='Site.match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='firstParticipant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstParticipant', to='Site.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='secondParticipant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondParticipant', to='Site.participant'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sport',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Site.sport'),
            preserve_default=False,
        ),
    ]
