# Generated by Django 5.0.4 on 2024-04-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_sport_rename_score1_match_firstparticipantscore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='startDate',
        ),
    ]
