# Generated by Django 5.0.4 on 2024-04-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_remove_tournament_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(related_name='tournaments', to='Site.participant'),
        ),
    ]
