# Generated by Django 5.0.4 on 2024-04-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_tournament_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='tournament',
        ),
        migrations.AddField(
            model_name='participant',
            name='tournaments',
            field=models.ManyToManyField(related_name='participantsTournaments', to='Site.tournament'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='match',
            field=models.ManyToManyField(related_name='participantsMatch', to='Site.match'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(related_name='tournamnentParticipants', to='Site.participant'),
        ),
    ]
