# Generated by Django 5.0.4 on 2024-04-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_remove_participant_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(related_name='tournamentParticipants', to='Site.participant'),
        ),
    ]
