# Generated by Django 5.0.4 on 2024-04-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_alter_tournament_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='isStarted',
            field=models.BooleanField(default=False),
        ),
    ]
