# Generated by Django 5.0.4 on 2024-04-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_match_isstarted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='isStarted',
        ),
        migrations.AddField(
            model_name='tournament',
            name='isStarted',
            field=models.BooleanField(default=False),
        ),
    ]
