# Generated by Django 5.0.4 on 2024-04-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_remove_match_isstarted_tournament_isstarted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='firstParticipantScore',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='secondParticipantScore',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='Site.participant'),
        ),
    ]
