# Generated by Django 5.0.4 on 2024-04-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_alter_match_firstparticipantscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='roundNumber',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
