# Generated by Django 5.0.4 on 2024-04-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_alter_match_secondparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
